name: Aperture
options:
  bundleIdPrefix: com.philagora.aperture
  developmentLanguage: en
  deploymentTarget:
    macOS: "26.0"
  createIntermediateGroups: false
  groupSortPosition: top
  generateEmptyDirectories: true
  findCarthageFrameworks: false
  defaultSourceDirectoryType: syncedFolder
  minimumXcodeGenVersion: 2.44.0

configs:
  Debug: debug
  Release: release

packages:
  SFSafeSymbols:
    url: https://github.com/SFSafeSymbols/SFSafeSymbols
    from: 5.3.0
  Pow:
    url: https://github.com/EmergeTools/Pow
    from: 1.0.5
  CombineAsync:
    url: https://github.com/hainayanda/CombineAsync.git
    from: 2.0.0
  AppInformation:
    url: https://github.com/sersoft-gmbh/app-information
    from: 1.11.1
  WelcomeWindow:
    url: https://github.com/CodeEditApp/WelcomeWindow
    branch: main
  AppState:
    url: https://github.com/0xLeif/AppState
    from: 2.2.0
  OnboardingKit:
    url: https://github.com/danielsaidi/OnboardingKit
    from: 9.2.0
  Engine:
    url: https://github.com/nathantannar4/Engine
    from: 2.5.0
  SwiftUIIntrospect:
    url: https://github.com/siteline/swiftui-introspect
    from: 26.0.0
  SwiftUIShimmer:
    url: https://github.com/markiv/SwiftUI-Shimmer.git
    from: 1.5.1

  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.4.0
  SQLiteData:
    url: https://github.com/pointfreeco/sqlite-data
    from: 1.5.2

targets:
  Aperture:
    type: application
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - path: Aperture
        excludes:
          - "**/.DS_Store"
      - path: Aperture/Assets.xcassets
        type: folder
        buildPhase: resources
    info:
      path: Aperture/Info.plist
      properties:
        CFBundleName: Aperture
        CFBundleDisplayName: Aperture
        CFBundleIdentifier: com.philagora.aperture
        CFBundleVersion: "1.0.0"
        CFBundlePrimaryIcon: AppIcon
        CFBundleShortVersionString: "1.0.0"
        LSMinimumSystemVersion: "26.0"
        NSPrincipalClass: NSApplication
        NSMainStoryboardFile: ""
        NSSupportsAutomaticTermination: true
        NSSupportsSuddenTermination: true
        LSApplicationCategoryType: public.app-category.video
        NSHighResolutionCapable: true
        NSScreenCaptureUsageDescription: "Aperture needs screen recording permission to capture your screen."
        NSCameraUsageDescription: "Aperture needs camera access to record video from your camera."
        NSMicrophoneUsageDescription: "Aperture needs microphone access to record audio."
        NSAppleMusicUsageDescription: "Aperture may access your music library for audio processing."
        NSDesktopFolderUsageDescription: "Aperture needs access to save recordings to your Desktop."
        NSDocumentsFolderUsageDescription: "Aperture needs access to save recordings to your Documents."
        NSDownloadsFolderUsageDescription: "Aperture needs access to save recordings to your Downloads."
        NSPhotoLibraryUsageDescription: "Aperture needs access to your Photos library to save recorded videos and export them to your photo collection."
        LSUIElement: false
        NSSupportsAutomaticGraphicsSwitching: true
        MetalCaptureEnabled: true
        NSRequiresAquaSystemAppearance: false
        UIBackgroundModes:
          - audio
          - background-processing
        CFBundleDocumentTypes:
          - CFBundleTypeName: Video
            CFBundleTypeRole: Editor
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - public.movie
              - public.mpeg-4
              - com.apple.quicktime-movie
              - public.avi
              - com.compuserve.gif
        UTImportedTypeDeclarations:
          - {}
    entitlements:
      path: Aperture/Aperture.entitlements
      properties:
        com.apple.developer.aps-environment: development
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.files.downloads.read-write: true
        com.apple.security.personal-information.photos-library: true
        com.apple.security.assets.music.read-write: true
        com.apple.security.device.camera: true
        com.apple.security.device.audio-input: true
        com.apple.security.cs.allow-jit: true
        com.apple.security.cs.allow-unsigned-executable-memory: true
        com.apple.security.temporary-exception.mach-lookup.global-name:
          - com.apple.screencapture.interactive
          - com.apple.audio.toolbox.AURemoteIO
    settings:
      base:
        PRODUCT_NAME: Aperture
        PROJECT_NAME: Aperture
        PRODUCT_BUNDLE_IDENTIFIER: com.philagora.aperture
        DEVELOPMENT_TEAM: "FUU334NWUK"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        ENABLE_HARDENED_RUNTIME: true
        MACOSX_DEPLOYMENT_TARGET: "26.0"
        SWIFT_VERSION: "5.10"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: Aperture/Info.plist
        CODE_SIGN_ENTITLEMENTS: Aperture/Aperture.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_FILE_ACCESS_PICTURE_FOLDER: true
        ENABLE_FILE_ACCESS_MOVIES_FOLDER: true
        ENABLE_FILE_ACCESS_DOWNLOADS_FOLDER: true
        ENABLE_RESOURCE_ACCESS_AUDIO_INPUT: true
        ENABLE_RESOURCE_ACCESS_CAMERA: true
        ENABLE_USER_SELECTED_FILES: true
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        COMBINE_HIDPI_IMAGES: true
        SWIFT_EMIT_LOC_STRINGS: true
        SWIFT_OBJC_BRIDGING_HEADER: ""
        SWIFT_STRICT_CONCURRENCY: minimal
        GCC_C_LANGUAGE_STANDARD: c17
        CLANG_CXX_LANGUAGE_STANDARD: "c++20"
        METAL_ENABLE_DEBUG_INFO: true
        MTL_ENABLE_DEBUG_INFO: true
        INFOPLIST_KEY_CFBundleDisplayName: Aperture
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.photo-video
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Aperture needs access to your photo library to import photos."
        ENABLE_STRICT_OBJC_MSGSEND: true
        ENABLE_TESTABILITY: false
        CLANG_ENABLE_MODULES: true
        CLANG_ENABLE_OBJC_ARC: true
        OTHER_LDFLAGS:
          - "-framework AVFoundation"
          - "-framework ScreenCaptureKit"
          - "-framework CoreMedia"
          - "-framework AVKit"
          - "-framework Accelerate"
          - "-framework Metal"
          - "-framework CoreAudio"
          - "-framework AudioToolbox"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS:
            - DEBUG
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          GCC_OPTIMIZATION_LEVEL: "0"
          ONLY_ACTIVE_ARCH: true
          ENABLE_TESTABILITY: true
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
          GCC_OPTIMIZATION_LEVEL: "3"
          ENABLE_TESTABILITY: false
          LLVM_LTO: true
          DEAD_CODE_STRIPPING: true
          STRIP_INSTALLED_PRODUCT: true
    dependencies:
      - package: SFSafeSymbols
      - package: Pow
      - package: CombineAsync
      - package: AppInformation
      - package: WelcomeWindow
      - package: AppState
      - package: OnboardingKit
      - package: Engine
      - package: SwiftUIIntrospect
      - package: SwiftUIShimmer
        product: Shimmer

      - package: KeyboardShortcuts
      - package: SQLiteData
      - sdk: AVFoundation.framework
      - sdk: ScreenCaptureKit.framework
      - sdk: CoreMedia.framework
      - sdk: AVKit.framework
      - sdk: Accelerate.framework
      - sdk: Metal.framework
      - sdk: CoreAudio.framework
      - sdk: AudioToolbox.framework
      - sdk: Cocoa.framework
      - sdk: SwiftUI.framework
      - sdk: Combine.framework
      - sdk: UniformTypeIdentifiers.framework
      - sdk: CoreVideo.framework
      - sdk: VideoToolbox.framework
      - sdk: CoreImage.framework
      - sdk: QuartzCore.framework
      - sdk: CoreGraphics.framework
      - sdk: IOKit.framework
      - sdk: Security.framework

schemes:
  Aperture:
    build:
      targets:
        Aperture: all
    run:
      config: Debug
      commandLineArguments: {}
      environmentVariables: {}
    test:
      config: Debug
      gatherCoverageData: false
      commandLineArguments: {}
      environmentVariables: {}
    profile:
      config: Release
      commandLineArguments: {}
      environmentVariables: {}
    analyze:
      config: Debug
    archive:
      config: Release
